import json
import pathlib

from celery import shared_task
from django.utils import timezone
from datetime import timedelta

_DATASET_PATH = pathlib.Path(__file__).resolve().parent.parent / "ml" / "Fruit And Vegetable Diseases Dataset"
_METRICS_PATH = pathlib.Path(__file__).resolve().parent.parent / "ml" / "saved_models" / "model_metrics.json"


@shared_task(bind=True, max_retries=0)
def evaluate_model_after_upload(self, model_version: str):
    """Run ml.evaluate after a new model is uploaded and persist results to model_metrics.json."""
    import numpy as np
    from sklearn.metrics import classification_report, confusion_matrix
    import torch
    from torch.utils.data import DataLoader, random_split
    from torchvision import transforms
    from ml.model import load_model
    from ml.train import HealthyRottenDataset, SEED
    from ml.evaluate import _save_confusion_matrix, CM_SAVE_PATH, MODEL_PATH, IMG_SIZE, BATCH_SIZE, VAL_SPLIT
    import os

    tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    full_dataset = HealthyRottenDataset(root=str(_DATASET_PATH), transform=tf)
    n_val = max(1, int(VAL_SPLIT * len(full_dataset)))
    n_train = len(full_dataset) - n_val
    _, val_set = random_split(
        full_dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(SEED),
    )

    _in_docker = pathlib.Path("/.dockerenv").exists()
    num_workers = 0 if (os.name == "nt" or _in_docker) else 2
    loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=False, num_workers=num_workers)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = load_model(str(MODEL_PATH), device=device)

    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            preds = model(images).argmax(dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    report = classification_report(all_labels, all_preds, target_names=["Healthy", "Rotten"], output_dict=True)
    cm = confusion_matrix(all_labels, all_preds)
    _save_confusion_matrix(cm, CM_SAVE_PATH)

    metrics = {
        "model_version": model_version,
        "updated_at": timezone.now().strftime("%Y-%m-%d"),
        "dataset": "Fruit and Vegetable Disease (Healthy vs Rotten) \u2014 Kaggle",
        "train_samples": n_train,
        "val_samples": n_val,
        "accuracy": round(report["accuracy"], 4),
        "precision": round(report["macro avg"]["precision"], 4),
        "recall": round(report["macro avg"]["recall"], 4),
        "f1_score": round(report["macro avg"]["f1-score"], 4),
        "auc_roc": None,
        "confusion_matrix": {
            "true_positive": int(cm[1, 1]),
            "true_negative": int(cm[0, 0]),
            "false_positive": int(cm[0, 1]),
            "false_negative": int(cm[1, 0]),
        },
        "notes": "Auto-generated by evaluate_model_after_upload Celery task.",
    }
    _METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(_METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)

    return f"Evaluation complete: accuracy={metrics['accuracy']}"


@shared_task
def cleanup_stale_reservations():
    """Remove CartReservations older than 2 hours (abandoned carts)."""
    from api.models import CartReservation
    cutoff = timezone.now() - timedelta(hours=2)
    deleted, _ = CartReservation.objects.filter(updated_at__lt=cutoff).delete()
    return f"Deleted {deleted} stale cart reservations"


@shared_task
def expire_pending_orders():
    """
    Cancel vendor Orders that have passed their expires_at deadline
    without being confirmed by the producer.
    Only Pending orders are expired — once confirmed/ready/delivered they
    are no longer cancellable by this task.
    """
    from api.models import Order
    now = timezone.now()
    expired_qs = Order.objects.filter(
        status="Pending",
        expires_at__isnull=False,
        expires_at__lte=now,
    )
    count = expired_qs.count()
    expired_qs.update(status="Cancelled")
    return f"Expired {count} pending orders"
