"""
Evaluation script – run after training to get precision, recall, F1, confusion matrix.

Usage (from backend-fastapi/):
    python -m ml.evaluate --data_dir "../Fruit And Vegetable Diseases Dataset"

Evaluates on a held-out 20% test split (same seed as training so there is
zero overlap with the training data).  Prints per-class metrics and saves a
confusion matrix PNG to ml/saved_models/confusion_matrix.png.

Author (ai-eval): Member 2
Evidence prefix: ai-eval
"""

import argparse
import os
import pathlib

import matplotlib
matplotlib.use("Agg")   # non-interactive backend — safe inside Docker/CI
import matplotlib.pyplot as plt
import numpy as np
import torch
from sklearn.metrics import classification_report, confusion_matrix
from torch.utils.data import DataLoader


from ml.data.preprocess import build_splits, SEED, VAL_SPLIT
from ml.model import load_model

MODEL_PATH   = pathlib.Path(__file__).parent / "saved_models" / "quality_classifier.pt"
CM_SAVE_PATH = pathlib.Path(__file__).parent / "saved_models" / "confusion_matrix.png"
BATCH_SIZE   = 32

_IN_DOCKER  = pathlib.Path("/.dockerenv").exists()
NUM_WORKERS = 0 if (os.name == "nt" or _IN_DOCKER) else 2


def _save_confusion_matrix(cm: np.ndarray, save_path: pathlib.Path) -> None:
    """Save a labelled confusion matrix as a PNG file."""
    fig, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(cm, interpolation="nearest", cmap=plt.cm.Blues)
    plt.colorbar(im, ax=ax)

    classes = ["Healthy", "Rotten"]
    tick_marks = range(len(classes))
    ax.set_xticks(tick_marks)
    ax.set_yticks(tick_marks)
    ax.set_xticklabels(classes)
    ax.set_yticklabels(classes)

    # Annotate each cell with its count
    thresh = cm.max() / 2.0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(
                j, i, str(cm[i, j]),
                ha="center", va="center",
                color="white" if cm[i, j] > thresh else "black",
            )

    ax.set_ylabel("Actual label")
    ax.set_xlabel("Predicted label")
    ax.set_title("Confusion Matrix – Quality Classifier")
    fig.tight_layout()
    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"  Confusion matrix saved → {save_path}")




def save_metrics_json(report: dict, cm: np.ndarray, n_train: int, n_val: int, model_version: str) -> None:
    import json
    from datetime import date
    metrics = {
        "model_version": model_version,
        "updated_at": date.today().isoformat(),
        "dataset": "Fruit and Vegetable Disease (Healthy vs Rotten) \u2014 Kaggle",
        "train_samples": n_train,
        "val_samples": n_val,
        "accuracy": round(report["accuracy"], 4),
        "precision": round(report["macro avg"]["precision"], 4),
        "recall": round(report["macro avg"]["recall"], 4),
        "f1_score": round(report["macro avg"]["f1-score"], 4),
        "auc_roc": None,
        "confusion_matrix": {
            "true_positive": int(cm[1, 1]),
            "true_negative": int(cm[0, 0]),
            "false_positive": int(cm[0, 1]),
            "false_negative": int(cm[1, 0]),
        },
        "notes": "Auto-generated by ml.evaluate.",
    }
    json_path = MODEL_PATH.parent / "model_metrics.json"
    with open(json_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"  Metrics saved → {json_path}")


def evaluate(data_dir: str, model_version: str = "mobilenetv2-v2") -> None:
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"No trained model at {MODEL_PATH}. Run ml/train.py first.")

    _, val_set, n_train, n_val = build_splits(data_dir)
    print(f"Evaluating on {n_val} held-out samples ({VAL_SPLIT:.0%} split, seed={SEED})")

    loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = load_model(str(MODEL_PATH), device=device)

    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    print("\n── Classification Report ─────────────────────────────────")
    report = classification_report(all_labels, all_preds, target_names=["Healthy", "Rotten"], output_dict=True)
    print(classification_report(all_labels, all_preds, target_names=["Healthy", "Rotten"]))

    cm = confusion_matrix(all_labels, all_preds)
    print("Confusion matrix (rows=actual, cols=predicted):")
    print(f"             Healthy  Rotten")
    print(f"  Healthy    {cm[0,0]:>7}  {cm[0,1]:>6}")
    print(f"  Rotten     {cm[1,0]:>7}  {cm[1,1]:>6}")

    _save_confusion_matrix(cm, CM_SAVE_PATH)

    healthy_mask = all_labels == 0
    hit_rate = (all_preds[healthy_mask] == 0).mean() if healthy_mask.any() else 0.0
    print(f"\nHit-rate (healthy correctly identified): {hit_rate:.3f}")

    save_metrics_json(report, cm, n_train, n_val, model_version)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate quality classifier on held-out val split")
    parser.add_argument("--data_dir", required=True, help="Path to dataset root folder")
    parser.add_argument("--model_version", default="mobilenetv2-v2", help="Version label for metrics JSON")
    args = parser.parse_args()
    evaluate(args.data_dir, model_version=args.model_version)
