# Generated by Django 5.1.5 on 2026-03-16 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality_checks/')),
                ('grade', models.CharField(choices=[('A', 'Grade A – Premium'), ('B', 'Grade B – Standard'), ('C', 'Grade C – Discounted')], max_length=1)),
                ('color_score', models.FloatField(help_text='Colour uniformity score 0–100')),
                ('size_score', models.FloatField(help_text='Size / shape score 0–100')),
                ('ripeness_score', models.FloatField(help_text='Ripeness / freshness score 0–100')),
                ('model_confidence', models.FloatField(help_text='CNN softmax confidence 0–1')),
                ('model_version', models.CharField(default='mobilenetv2-v1', max_length=50)),
                ('is_healthy', models.BooleanField()),
                ('notes', models.TextField(blank=True, default='')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='api.product')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
