# Generated by Django 5.1.5 on 2026-04-22 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_modelevaluation"),
        ("api", "0015_qualityoverride"),
    ]

    operations = []
