# Generated by Django 5.1.5 on 2026-04-28 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_product_ai_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringorder",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Recurring order will stop after this date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recurringorder",
            name="pause_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price_changed", "Price changed"),
                    ("out_of_stock", "Out of stock"),
                    ("quantity_unavailable", "Quantity unavailable"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="recurringorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused — awaiting approval"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ai_discount_active",
            field=models.BooleanField(
                default=False,
                help_text="True when the current AI quality discount is active.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.IntegerField(
                default=0, help_text="Manual surplus discount 0–50%"
            ),
        ),
        migrations.AlterField(
            model_name="qualityoverride",
            name="reason",
            field=models.CharField(
                choices=[
                    ("wrong_grade", "AI grade was incorrect"),
                    ("context", "Context the model could not see (e.g. variety, age)"),
                    ("image_quality", "Poor image quality affected the result"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RecurringOrderNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("price_changed", "Price changed"),
                            ("out_of_stock", "Out of stock"),
                            ("quantity_unavailable", "Quantity unavailable"),
                            ("order_placed", "Order placed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("requires_action", models.BooleanField(default=True)),
                (
                    "action_taken",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recurring_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.recurringorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
