# Generated by Django 5.1.5 on 2026-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_recurring_order_status_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringorder",
            name="on_price_change",
            field=models.CharField(
                choices=[
                    ("auto_continue", "Yes — continue automatically"),
                    ("pause_notify", "No — pause and notify me"),
                ],
                default="pause_notify",
                help_text="What to do if a product price changes before the order fires",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recurringorder",
            name="on_quantity_change",
            field=models.CharField(
                choices=[
                    ("auto_continue", "Yes — continue automatically"),
                    ("pause_notify", "No — pause and notify me"),
                ],
                default="pause_notify",
                help_text="What to do if the requested quantity is not fully available",
                max_length=20,
            ),
        ),
    ]
