# Generated by Django 5.1.5 on 2026-05-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_product_pending_approval_admiinotp'),
        ('api', '0021_paymentsettlement'),
    ]

    operations = [
    ]
