# Generated by Django 5.1.5 on 2026-05-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260501_1231'),
        ('api', '0023_user_email_verified_alter_adminotp_id_and_more'),
    ]

    operations = [
    ]
