# Generated by Django 5.1.5 on 2026-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20260506_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ai_discount_active',
            field=models.BooleanField(default=False, help_text='True when the current AI quality discount is active.', verbose_name='AI discount active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_discount_percentage',
            field=models.IntegerField(default=0, help_text='AI quality discount 0–50%', verbose_name='Quality-check discount (AI)'),
        ),
    ]
