# Generated by Django 5.1.5 on 2026-05-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20260506_2007'),
        ('api', '0024_phone_surplus_order_customer'),
    ]

    operations = [
    ]
